-- JurisFlow / Supabase schema
-- Execute this in the Supabase SQL editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  timestamp text not null,
  nome text not null,
  escritorio text not null,
  cargo text,
  email text not null,
  whatsapp text not null,
  cidade_estado text,
  area text,
  porte text,
  volume text,
  objetivo text,
  prioridade text,
  sistemas text,
  principal_gargalo text not null,
  observacoes text,
  consentimento text not null
);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null,
  password_hash text not null,
  role text not null default 'cliente',
  active boolean not null default true,
  created_at text not null,
  updated_at text not null
);

create index if not exists leads_timestamp_idx on public.leads (timestamp desc);
create index if not exists leads_email_idx on public.leads (email);
create index if not exists usuarios_username_idx on public.usuarios (username);
